Server:
  Runmode: debug
  HttpPort: 7788
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix:
  Charser: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenonns: 30